"""created offer models

Revision ID: 024777d7410c
Revises: e12a0ed38c41
Create Date: 2026-05-13 12:16:30.116692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024777d7410c'
down_revision: Union[str, Sequence[str], None] = 'e12a0ed38c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('ITEM', 'CATEGORY', 'STORE', 'BOGO', 'COUPON', name='offertype'), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FLAT', 'FREE_ITEM', 'MINIMUM_PURCHASE', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_limit_per_user', sa.Integer(), nullable=True),
    sa.Column('usage_limit_total', sa.Integer(), nullable=True),
    sa.Column('min_spent_amount', sa.Float(), nullable=True),
    sa.Column('max_discount_amount', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_name'), 'offers', ['name'], unique=False)
    op.create_table('offer_bogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('buy_quantity', sa.Integer(), nullable=False),
    sa.Column('get_quantity', sa.Integer(), nullable=False),
    sa.Column('apply_to_same_item', sa.Boolean(), nullable=True),
    sa.Column('get_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_bogo_id'), 'offer_bogo', ['id'], unique=False)
    op.create_table('offer_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.Enum('ITEM', 'CATEGORY', 'STORE', name='targettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_targets_id'), 'offer_targets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_targets_id'), table_name='offer_targets')
    op.drop_table('offer_targets')
    op.drop_index(op.f('ix_offer_bogo_id'), table_name='offer_bogo')
    op.drop_table('offer_bogo')
    op.drop_index(op.f('ix_offers_name'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
