"""added type field in career model

Revision ID: 052b97805fac
Revises: 3b20abb4a287
Create Date: 2026-06-23 14:31:42.805429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052b97805fac'
down_revision: Union[str, Sequence[str], None] = '3b20abb4a287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('careers', 'type')
    # ### end Alembic commands ###
