"""update in business model

Revision ID: 1a70da95e72f
Revises: 864ef6aec006
Create Date: 2026-06-30 12:26:26.121607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a70da95e72f'
down_revision: Union[str, Sequence[str], None] = '864ef6aec006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('business_subscriptions_user_id_fkey'), 'business_subscriptions', type_='foreignkey')
    op.drop_column('business_subscriptions', 'user_id')
    op.add_column('businesses', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'user_id')
    op.add_column('business_subscriptions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('business_subscriptions_user_id_fkey'), 'business_subscriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
