"""create combo offer model

Revision ID: 1fb91a840fae
Revises: 89a186d78d30
Create Date: 2026-05-27 12:11:37.402158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb91a840fae'
down_revision: Union[str, Sequence[str], None] = '89a186d78d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combo_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('discount_type', sa.Enum('COMBO_PRICE', 'FIXED', 'PERCENTAGE', name='combodiscounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_offer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combo_offer_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['combo_offer_id'], ['combo_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combo_offer_items')
    op.drop_table('combo_offers')
    # ### end Alembic commands ###
