"""SubscriptionPlan model

Revision ID: 2ab13db65430
Revises: 444afbad4e7d
Create Date: 2026-06-17 12:20:33.565678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab13db65430'
down_revision: Union[str, Sequence[str], None] = '444afbad4e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_period', sa.String(length=50), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_locations', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.drop_index(op.f('ix_demo_requests_id'), table_name='demo_requests')
    op.drop_constraint(op.f('demo_requests_user_id_fkey'), 'demo_requests', type_='foreignkey')
    op.create_foreign_key(None, 'demo_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demo_requests', type_='foreignkey')
    op.create_foreign_key(op.f('demo_requests_user_id_fkey'), 'demo_requests', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_demo_requests_id'), 'demo_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
