"""add billing and shipping address

Revision ID: 42550146f12a
Revises: 63a46a93586c
Create Date: 2026-08-11 13:47:42.363794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42550146f12a'
down_revision: Union[str, Sequence[str], None] = '63a46a93586c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('billing_address_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('shipping_full_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_company', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(length=15), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_line_1', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_line_2', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_longitude', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['shipping_address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'addresses', ['billing_address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_longitude')
    op.drop_column('orders', 'shipping_latitude')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address_line_2')
    op.drop_column('orders', 'shipping_address_line_1')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_company')
    op.drop_column('orders', 'shipping_full_name')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_column('orders', 'billing_address_id')
    # ### end Alembic commands ###
