"""delivery config model

Revision ID: 4291d221a065
Revises: 8116cd5f4969
Create Date: 2026-06-03 14:44:09.972817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4291d221a065'
down_revision: Union[str, Sequence[str], None] = '8116cd5f4969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_distance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('delivery_fee >= 0', name='check_delivery_fee_positive'),
    sa.CheckConstraint('max_distance IS NULL OR max_distance > min_distance', name='check_max_greater_than_min'),
    sa.CheckConstraint('min_distance >= 0', name='check_min_distance_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_configs')
    # ### end Alembic commands ###
