"""update product tables

Revision ID: 431ff3dd71a0
Revises: 7de8751dff94
Create Date: 2026-07-05 13:45:11.996397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431ff3dd71a0'
down_revision: Union[str, Sequence[str], None] = '7de8751dff94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_attributes', 'value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('uq_product_categories_name_active', 'product_categories', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_product_option'), 'product_options', type_='unique')
    op.create_index('uq_product_option_active', 'product_options', ['product_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('product_variants', sa.Column('features', sa.Text(), nullable=True))
    op.add_column('product_variants', sa.Column('description', sa.Text(), nullable=True))
    op.create_index('uq_products_sku_active', 'product_variants', ['sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('products', sa.Column('features', sa.Text(), nullable=True))
    op.create_index('uq_product_name_active', 'products', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_option_value'), 'variant_option_values', type_='unique')
    op.create_index('uq_option_value_active', 'variant_option_values', ['option_id', 'value'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_option_value_active', table_name='variant_option_values', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_option_value'), 'variant_option_values', ['option_id', 'value'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_product_categories_name_active', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('products', 'features')
    op.drop_index('uq_products_sku_active', table_name='product_variants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('product_variants', 'description')
    op.drop_column('product_variants', 'features')
    op.drop_index('uq_product_option_active', table_name='product_options', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_product_option'), 'product_options', ['product_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_product_categories_name_active', table_name='product_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.alter_column('product_attributes', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
