"""Demo request model

Revision ID: 444afbad4e7d
Revises: b149adb34e44
Create Date: 2026-06-17 10:41:22.854257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444afbad4e7d'
down_revision: Union[str, Sequence[str], None] = 'b149adb34e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_size', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.Text(), nullable=True),
    sa.Column('branch_count', sa.Integer(), nullable=False),
    sa.Column('opening_type', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('preferred_date', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'SCHEDULED', 'COMPLETED', 'CANCELLED', name='demorequeststatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_requests_id'), 'demo_requests', ['id'], unique=False)
    op.alter_column('combo_offers', 'discount_value',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('combo_offers', 'discount_value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_demo_requests_id'), table_name='demo_requests')
    op.drop_table('demo_requests')
    # ### end Alembic commands ###
