"""create SubscriptionPlanAddonPrice model

Revision ID: 50347f9e96d8
Revises: 1a70da95e72f
Create Date: 2026-07-02 12:36:14.135042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50347f9e96d8'
down_revision: Union[str, Sequence[str], None] = '1a70da95e72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plan_addon_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_addon_id', sa.Integer(), nullable=False),
    sa.Column('billing_period', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_addon_id'], ['subscription_plan_addons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_plan_addon_id', 'billing_period', name='uq_addon_billing_period')
    )
    op.create_index(op.f('ix_subscription_plan_addon_prices_subscription_plan_addon_id'), 'subscription_plan_addon_prices', ['subscription_plan_addon_id'], unique=False)
    op.drop_column('subscription_plan_addons', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plan_addons', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscription_plan_addon_prices_subscription_plan_addon_id'), table_name='subscription_plan_addon_prices')
    op.drop_table('subscription_plan_addon_prices')
    # ### end Alembic commands ###
