"""added soft-delete in offer and cart model

Revision ID: 51e3c6e39fcc
Revises: 6e63156cebfc
Create Date: 2026-06-18 11:17:59.757812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e3c6e39fcc'
down_revision: Union[str, Sequence[str], None] = '6e63156cebfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('carts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('combo_offer_items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('combo_offers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('offer_bogo', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('offer_targets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('offers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'deleted_at')
    op.drop_column('offer_targets', 'deleted_at')
    op.drop_column('offer_bogo', 'deleted_at')
    op.drop_column('combo_offers', 'deleted_at')
    op.drop_column('combo_offer_items', 'deleted_at')
    op.drop_column('carts', 'deleted_at')
    op.drop_column('cart_items', 'deleted_at')
    # ### end Alembic commands ###
