"""create service, subscriptionPlanPrice, subscriptionPlanAddon models

Revision ID: 6edd139ef552
Revises: 052b97805fac
Create Date: 2026-06-24 16:45:02.196825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edd139ef552'
down_revision: Union[str, Sequence[str], None] = '052b97805fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_type', sa.String(length=255), nullable=False),
    sa.Column('badge', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sub_title', sa.Text(), nullable=True),
    sa.Column('bottom_card', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('subscription_plan_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plan_addons_id'), 'subscription_plan_addons', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plan_addons_subscription_plan_id'), 'subscription_plan_addons', ['subscription_plan_id'], unique=False)
    op.create_table('subscription_plan_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_period', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_plan_id', 'billing_period', name='uq_plan_billing_period')
    )
    op.create_index(op.f('ix_subscription_plan_prices_id'), 'subscription_plan_prices', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plan_prices_subscription_plan_id'), 'subscription_plan_prices', ['subscription_plan_id'], unique=False)
    op.add_column('subscription_plans', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('subscription_plans', sa.Column('features', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('subscription_plans_key_key'), 'subscription_plans', type_='unique')
    op.drop_constraint(op.f('subscription_plans_slug_key'), 'subscription_plans', type_='unique')
    op.create_index(op.f('ix_subscription_plans_key'), 'subscription_plans', ['key'], unique=True)
    op.create_index(op.f('ix_subscription_plans_service_id'), 'subscription_plans', ['service_id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.create_foreign_key(None, 'subscription_plans', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscription_plans', 'billing_period')
    op.drop_column('subscription_plans', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('billing_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscription_plans', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_service_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_key'), table_name='subscription_plans')
    op.create_unique_constraint(op.f('subscription_plans_slug_key'), 'subscription_plans', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('subscription_plans_key_key'), 'subscription_plans', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscription_plans', 'features')
    op.drop_column('subscription_plans', 'service_id')
    op.drop_index(op.f('ix_subscription_plan_prices_subscription_plan_id'), table_name='subscription_plan_prices')
    op.drop_index(op.f('ix_subscription_plan_prices_id'), table_name='subscription_plan_prices')
    op.drop_table('subscription_plan_prices')
    op.drop_index(op.f('ix_subscription_plan_addons_subscription_plan_id'), table_name='subscription_plan_addons')
    op.drop_index(op.f('ix_subscription_plan_addons_id'), table_name='subscription_plan_addons')
    op.drop_table('subscription_plan_addons')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
