"""create variant options and value model

Revision ID: 79ac80098ade
Revises: 236d250aa0a4
Create Date: 2026-06-21 11:05:13.897636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ac80098ade'
down_revision: Union[str, Sequence[str], None] = '236d250aa0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_product_option')
    )
    op.create_index(op.f('ix_product_options_id'), 'product_options', ['id'], unique=False)
    op.create_index(op.f('ix_product_options_product_id'), 'product_options', ['product_id'], unique=False)
    op.create_table('variant_option_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['product_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'value', name='uq_option_value')
    )
    op.create_index(op.f('ix_variant_option_values_id'), 'variant_option_values', ['id'], unique=False)
    op.create_index(op.f('ix_variant_option_values_option_id'), 'variant_option_values', ['option_id'], unique=False)
    op.create_table('product_variant_options_value',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('variant_option_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['variant_option_value_id'], ['variant_option_values.id'], ),
    sa.PrimaryKeyConstraint('product_variant_id', 'variant_option_value_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variant_options_value')
    op.drop_index(op.f('ix_variant_option_values_option_id'), table_name='variant_option_values')
    op.drop_index(op.f('ix_variant_option_values_id'), table_name='variant_option_values')
    op.drop_table('variant_option_values')
    op.drop_index(op.f('ix_product_options_product_id'), table_name='product_options')
    op.drop_index(op.f('ix_product_options_id'), table_name='product_options')
    op.drop_table('product_options')
    # ### end Alembic commands ###
