"""add soft delete in product models

Revision ID: 7de8751dff94
Revises: 8368273666ec
Create Date: 2026-07-05 12:33:18.211382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de8751dff94'
down_revision: Union[str, Sequence[str], None] = '8368273666ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_attributes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('product_categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('product_options', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('product_variant_images', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('product_variants', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('variant_option_values', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_option_values', 'deleted_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('product_variants', 'deleted_at')
    op.drop_column('product_variant_images', 'deleted_at')
    op.drop_column('product_options', 'deleted_at')
    op.drop_column('product_categories', 'deleted_at')
    op.drop_column('product_attributes', 'deleted_at')
    # ### end Alembic commands ###
