"""fields added in cart models

Revision ID: 8116cd5f4969
Revises: 1fb91a840fae
Create Date: 2026-05-28 12:59:06.814958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8116cd5f4969'
down_revision: Union[str, Sequence[str], None] = '1fb91a840fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('is_free_item', sa.Boolean(), nullable=True))
    op.add_column('cart_items', sa.Column('trigger_cart_item_id', sa.Integer(), nullable=True))
    op.add_column('cart_items', sa.Column('parent_offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'offers', ['parent_offer_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'cart_items', ['trigger_cart_item_id'], ['id'])
    op.add_column('carts', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carts', 'offers', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'coupon_id')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'parent_offer_id')
    op.drop_column('cart_items', 'trigger_cart_item_id')
    op.drop_column('cart_items', 'is_free_item')
    # ### end Alembic commands ###
