"""update order model

Revision ID: 8368273666ec
Revises: 50347f9e96d8
Create Date: 2026-07-02 13:28:01.670399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8368273666ec'
down_revision: Union[str, Sequence[str], None] = '50347f9e96d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'offers', ['coupon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'coupon_id')
    # ### end Alembic commands ###
