"""update fields in business-detail model

Revision ID: 864ef6aec006
Revises: ffdf9ded5ef2
Create Date: 2026-06-30 12:10:12.278762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '864ef6aec006'
down_revision: Union[str, Sequence[str], None] = 'ffdf9ded5ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_subscriptions', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('business_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('business_subscriptions', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
