"""added buy_item_id field in offerbogo table

Revision ID: 90e60886d085
Revises: 024777d7410c
Create Date: 2026-05-13 13:53:58.614033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e60886d085'
down_revision: Union[str, Sequence[str], None] = '024777d7410c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_bogo', sa.Column('buy_item_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer_bogo', 'buy_item_id')
    # ### end Alembic commands ###
