"""tax config model

Revision ID: add0aafb8637
Revises: 4291d221a065
Create Date: 2026-06-03 15:39:21.926665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add0aafb8637'
down_revision: Union[str, Sequence[str], None] = '4291d221a065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tax_scope', sa.Enum('PRODUCT', 'SUBSCRIPTION', 'SERVICE', 'SHIPPING', 'GLOBAL', name='taxscope'), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_taxes_id'), 'taxes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxes_id'), table_name='taxes')
    op.drop_table('taxes')
    # ### end Alembic commands ###
