"""Cart order relation

Revision ID: b149adb34e44
Revises: e4c2aef80fa2
Create Date: 2026-06-09 11:26:12.570955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b149adb34e44'
down_revision: Union[str, Sequence[str], None] = 'e4c2aef80fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['cart_id'])
    op.create_foreign_key(None, 'orders', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'cart_id')
    # ### end Alembic commands ###
