"""Create refund model

Revision ID: e028ce4b7b54
Revises: 42550146f12a
Create Date: 2026-08-14 09:56:57.199443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e028ce4b7b54'
down_revision: Union[str, Sequence[str], None] = '42550146f12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('processed_by_id', sa.UUID(), nullable=True),
    sa.Column('refund_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_refunded_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('refund_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('gateway_response_code', sa.String(length=5), nullable=True),
    sa.Column('gateway_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_original_transaction_id'), 'refunds', ['original_transaction_id'], unique=False)
    op.create_index(op.f('ix_refunds_processed_by_id'), 'refunds', ['processed_by_id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_transaction_id'), 'refunds', ['refund_transaction_id'], unique=True)
    op.create_index(op.f('ix_refunds_refund_type'), 'refunds', ['refund_type'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_refund_type'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_refund_transaction_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_processed_by_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_original_transaction_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
