"""added image_url field in combooffer model

Revision ID: e4c2aef80fa2
Revises: ebfc59af1305
Create Date: 2026-06-08 13:12:17.438743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c2aef80fa2'
down_revision: Union[str, Sequence[str], None] = 'ebfc59af1305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combo_offers', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('combo_offers', 'image_url')
    # ### end Alembic commands ###
