"""update product models

Revision ID: f50a884f62a7
Revises: 431ff3dd71a0
Create Date: 2026-07-05 13:53:49.957105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50a884f62a7'
down_revision: Union[str, Sequence[str], None] = '431ff3dd71a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    # ### end Alembic commands ###
